### ISSUE TITLE
Pau's toy task

### ISSUE THREAD

**Issue by mjrolland** [reconhub/tasks#11]
Creating a toy task helping Matthieu to finalise the platform's functionality 

[impact: Will help to finalise the platform's functionality]
[timeline: I am not sure what is a timeline in this context... The deadline when I need the task to be complete? Can you give more explanation?]
[originally proposed by @paujedynak]
[suggested repo: Do not know]
[additional notes:  thanks! great task :)]

**Comment by mjrolland** [comment]
hey Pau! thanks for doing this. Let me know if you got notification when task was validated and issue opened and also if you got notification for this comment

**Comment by paujedynak** [comment]
comment

**Comment by mjrolland** [comment]
reply
